### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by filipac** [rslb1/Working-EFI-OpenCore-0.6.5-MSI-Z390PRO#1]
Hello, I have the same configuration as you but it fails to start the installer for me. Anything special I need to do?

Here is the log 
[opencore-2021-02-17-200920.txt](https://github.com/rslb1/Working-EFI-OpenCore-0.6.5-MSI-Z390PRO/files/5998351/opencore-2021-02-17-200920.txt)

**Comment by rslb1** [comment]
Hey, please see the OpenCore troubleshooting page. This should have pretty much everything about what’s wrong with your OpenCore. Just try to find something relating to “stuck on ‘OCB: showing menu’..” 

Link to the troubleshooting page: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#table-of-contents

**Comment by filipac** [comment]
got it working, does audio work for you with alc 1?

**Comment by rslb1** [comment]
I’m not too sure off the top of my head. I will have to look at my set up. Maybe try and open my config.plist in OpenCore Configurator?
